PHACDataHub/pelias-canada

Rs-Pack/Dockerfile
Rs-Pack/package-lock.json
Rs-Pack/package.json
Rs-Pack/server.ts

Requesting your code review for using Deno and React Docker Image

Creating the Docker Image for the frontend UI

---

Rs-Pack/index.html
Rs-Pack/rspack.config.js
Rs-Pack/src/App.css
Rs-Pack/src/App.jsx

Reformated a few files with Prettier.
App.jsx
index.html
rspack.config
closes #30

Code format

---

ui/src/App.css
ui/src/App.jsx
ui/src/index.css

Cleaned up CSS to fix the width of the web page. It resizes dynamically with the window.
closes #29

fixed width to be dynamic and removed scroll bars

---

ui/src/App.css
ui/src/index.css
ui/src/layout/layout.jsx

Footer has been made sticky
closes #41

Made footer sticky

---

ui/index.html
ui/src/index.css
ui/src/layout/layout.jsx
ui/src/main.jsx

"Sticky" the footer to the bottom of the page, up until content pushes it further down.
Added a bunch of comments to help you follow my process here, since we couldn't get on a call to pair-program our way through this @samiatoui.

Footer positioning fix

---

package-lock.json

fix : remove orphan package-lock-json

---

ui/src/index.css
ui/src/layout/layout.jsx

Undone some CSS changes that have broken the footer

reverted to Stephen's changes

---

frontend/.eslintrc.cjs
frontend/package-lock.json
frontend/package.json
frontend/public/codeZips/DemoData.csv
frontend/public/codeZips/Python/batch_forwardGeocoder_Pelias_v4.py
frontend/public/codeZips/Python/batch_reverseGeocoder_Pelias_v4.py
frontend/public/codeZips/R/forwardGeocode_R_script_v1.r
frontend/public/codeZips/R/reverseGeocode_R_script_v1.r
frontend/public/locales/en/translation.json
frontend/public/locales/fr/translation.json
frontend/src/App.jsx
frontend/src/components/zipDowloads/PythonZipDownload.jsx
frontend/src/components/zipDowloads/RZipDownload.jsx
frontend/src/layout/TopNav.jsx
frontend/src/pages/apiPages/PythonApiPage.jsx
frontend/src/pages/apiPages/RShinyAPIPage.jsx

chore(ui): build zip for r and python api page

---

frontend/src/App.jsx
frontend/src/components/reverseBulkFetch/ReverseBulk.jsx
frontend/src/pages/bulkInput/ForwardBulkInput.jsx
frontend/src/pages/bulkInput/ReverseBulkInput.jsx

chorue(ui): make the reverse bulk similar to the forward bulk

---

frontend/src/layout/Layout.jsx

Change the GcdsNavLink from 16px to 20 px to conform to Gcds Design

fix: correct font size on GcdsNavLink

---

frontend/public/locales/en/translation.json
frontend/public/locales/fr/translation.json
frontend/src/layout/Layout.jsx

add on to issue #197 
completes the translation of aria label and text

fix(ui): translation added for skip-to-content accessibility

---

frontend/index.html
frontend/src/layout/Layout.jsx

a11y(ui): added dynamic page titles

---

frontend/public/locales/en/translation.json
frontend/public/locales/fr/translation.json

fix(ui): single input return date and time missing bracket added

---

frontend/src/layout/Layout.jsx

a11y(ui): toast container closes on language change - prevents error out

---

frontend/public/locales/en/translation.json
frontend/public/locales/fr/translation.json
frontend/server.ts
frontend/src/App.jsx
frontend/src/layout/Layout.jsx

chore(ui): Top nav and url update for ART4114

---

frontend/public/locales/en/translation.json
frontend/public/locales/fr/translation.json
frontend/src/pages/FAQ/FAQ.jsx

chore(ui): new visualization for the faq page

---

frontend/public/locales/en/translation.json
frontend/public/locales/fr/translation.json

a11y(ui): remove word click.

---

frontend/src/components/PercentageCircle.jsx
frontend/src/components/apiBulkInput/ForwardBulk.jsx
frontend/src/components/apiFetch/ResultsMap.css
frontend/src/components/apiFetch/ResultsSingleFetch.jsx
frontend/src/components/map/MapComponent.jsx
frontend/src/components/reverseBulkFetch/ReverseBulk.jsx

closes #245 
Closes #312 
closes #311 
closes #232 
#231 
#208

fix(ui): make changes to maps and legends

---

frontend/src/components/apiFetch/ForwardSingleFetch.jsx
frontend/src/components/apiFetch/ResultsSingleFetch.jsx
frontend/src/components/apiFetch/ReverseSingleFetch.jsx
frontend/src/components/apiFetch/UseLocationButton.jsx
frontend/src/pages/landingPage/Landingpage.jsx

a11y(ui): fix heading levels on landing page

---

frontend/public/locales/en/translation.json
frontend/public/locales/fr/translation.json
frontend/src/components/PercentageCircle.jsx
frontend/src/components/apiFetch/ForwardSingleFetch.jsx
frontend/src/components/apiFetch/ResultsSingleFetch.jsx
frontend/src/components/apiFetch/ReverseSingleFetch.jsx
frontend/src/components/apiFetch/UseLocationButton.jsx
frontend/src/pages/landingPage/Landingpage.jsx

chore(ui): landing page language changes

---

frontend/public/locales/en/translation.json
frontend/public/locales/fr/translation.json
frontend/src/components/apiFetch/ResultsSingleFetch.jsx
frontend/src/components/apiFetch/ReverseSingleFetch.jsx
frontend/src/components/apiFetch/UseLocationButton.jsx
frontend/src/pages/landingPage/Landingpage.jsx

closes #178
closes #179
closes #180
closes #181
closes #182
closes #185
closes #186
closes #191
closes #195
closes #206
closes #207
closes #217
closes #226
closes #248

chore(ui): translations on home page single fetch functions added

---

frontend/public/locales/en/translation.json
frontend/public/locales/fr/translation.json
frontend/src/components/map/MapComponent.jsx

fix(ui): map attribution removed

---

frontend/public/locales/en/translation.json
frontend/public/locales/fr/translation.json
frontend/src/pages/geocodingExplanation/GeocodingExplanation.css
frontend/src/pages/geocodingExplanation/GeocodingExplanation.jsx

choure(ui): updates to geo results exp page

---

Taskfile.yaml

Was missing permission in last PR - added now, and re-running

fix: added act-as permission for cloudbuild on cloud function build sa

---

frontend/package-lock.json

- @cdssnc/gcds-components to 0.35.0
- @cdssnc/gcds-components-react to 0.35.0
- @vitejs/plugin-react-swc to 3.10.2
- eslint to 9.28.0
- i18next to 25.2.1
- i18next-browser-languagedetector to 8.2.0
- react-router-dom to latest

chore(deps): update frontend dependencies
